# Week 1: Foundations — Cleaning and Exploring the Applicant Dataset

**Intern:** Meerab Asif  
**Organization:** NextGen Learners  
**Objective:** To practice data cleaning, data wrangling, and exploratory analysis using Python and Pandas.

## Initial Data Exploration

The dataset contains fictional applicant records. I will inspect its structure, identify missing values and duplicate records, and check for inconsistent formatting before cleaning the data.

In [1]:
import pandas as pd

df = pd.read_csv("C:\\Users\\AL-RASHEED\\Downloads\\applicants.csv")

print("Dataset shape:", df.shape)

display(df.head())

df.info()

print("\nMissing values:")
print(df.isnull().sum())

print("\nExact duplicate rows:")
print(df.duplicated().sum())

Dataset shape: (83, 7)

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
0,Ayesha Khan,AYESHA.KHAN1@EXAMPLE.COM,032-854-2679,web dev,Government College University,02/06/2026,Selected
1,Ali Raza,ali.raza2@example.com,03139345092,digital marketing,UET Lahore,2026-04-09,Under Review
2,Fatima Noor,NaN,03866306997,data science,Virtual University,2026-09-14,rejected
3,Hassan Ahmed,hassan.ahmed4@example.com,03655667651,data sci,Government College University,02/04/2026,Selected
4,Zainab Ali,zainab.ali5@example.com,031-489-2584,Data Analytics,Virtual University,2026-06-26,Under Review

<class 'pandas.DataFrame'>
RangeIndex: 83 entries, 0 to 82
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Applicant Name    81 non-null     str
 1   Email             81 non-null     str
 2   Phone             82 non-null     str
 3   Domain Applied    83 non-null     str
 4   University        81 non-null     str
 5   Application Date  82 non-null     str
 6   Status            81 non-null     str
dtypes: str(7)
memory usage: 4.7 KB

Missing values:
Applicant Name      2
Email               2
Phone               1
Domain Applied      0
University          2
Application Date    1
Status              2
dtype: int64

Exact duplicate rows:
3

## Initial Data Exploration

First, I checked the dataset's shape, columns, missing values, and duplicate records to understand its condition before cleaning.

In [2]:
df.isnull().sum()

Applicant Name      2
Email               2
Phone               1
Domain Applied      0
University          2
Application Date    1
Status              2
dtype: int64

In [3]:
before_rows = len(df)

df = df.dropna(subset=["Applicant Name", "Email"])

removed_rows = before_rows - len(df)

print("Rows removed:", removed_rows)
print("Remaining rows:", len(df))

Rows removed: 4
Remaining rows: 79

In [4]:
df["University"] = df["University"].fillna("Not Specified")

df["Status"] = df["Status"].fillna("Under Review")

In [5]:
print("Missing values after cleaning:")
print(df.isnull().sum())

Missing values after cleaning:
Applicant Name      0
Email               0
Phone               1
Domain Applied      0
University          0
Application Date    1
Status              0
dtype: int64

## Removing Duplicates

Exact duplicate rows were removed. Duplicate email addresses were also checked, keeping the first record for each email.

In [6]:
exact_duplicates = df.duplicated().sum()
df = df.drop_duplicates()
email_duplicates = df.duplicated(subset=["Email"]).sum()
df = df.drop_duplicates(subset=["Email"], keep="first")
print("Exact duplicates remaining:", df.duplicated().sum())

print(
    "Duplicate emails remaining:",
    df.duplicated(subset=["Email"]).sum()
)

Exact duplicates remaining: 0
Duplicate emails remaining: 0

## Standardizing Text

Extra spaces were removed from text fields. Applicant names were formatted consistently, and email addresses were converted to lowercase.

In [7]:
# Remove extra spaces from text columns
for col in df.select_dtypes(include=["object", "string"]).columns:
    df[col] = df[col].apply(
        lambda x: x.strip() if isinstance(x, str) else x
    )

# Standardize applicant names
df["Applicant Name"] = df["Applicant Name"].apply(
    lambda x: x.title() if isinstance(x, str) else x
)

# Standardize email addresses
df["Email"] = df["Email"].apply(
    lambda x: x.lower() if isinstance(x, str) else x
)

# Standardize application statuses
df["Status"] = df["Status"].apply(
    lambda x: x.strip().title() if isinstance(x, str) else x
)

print("Text formatting standardized successfully!")

Text formatting standardized successfully!

In [8]:
import pandas as pd

df = pd.read_csv("C:\\Users\\AL-RASHEED\\Downloads\\applicants.csv")

print("Dataset loaded successfully!")
display(df.head())

Dataset loaded successfully!

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
0,Ayesha Khan,AYESHA.KHAN1@EXAMPLE.COM,032-854-2679,web dev,Government College University,02/06/2026,Selected
1,Ali Raza,ali.raza2@example.com,03139345092,digital marketing,UET Lahore,2026-04-09,Under Review
2,Fatima Noor,NaN,03866306997,data science,Virtual University,2026-09-14,rejected
3,Hassan Ahmed,hassan.ahmed4@example.com,03655667651,data sci,Government College University,02/04/2026,Selected
4,Zainab Ali,zainab.ali5@example.com,031-489-2584,Data Analytics,Virtual University,2026-06-26,Under Review

In [9]:
# Remove extra spaces from all text columns
for col in df.select_dtypes(include=["object", "string"]).columns:
    df[col] = df[col].apply(
        lambda value: value.strip() if isinstance(value, str) else value
    )

# Standardize applicant names
df["Applicant Name"] = df["Applicant Name"].str.title()

# Standardize email addresses
df["Email"] = df["Email"].str.lower()

print("Text standardization completed!")
display(df.head())

Text standardization completed!

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
0,Ayesha Khan,ayesha.khan1@example.com,032-854-2679,web dev,Government College University,02/06/2026,Selected
1,Ali Raza,ali.raza2@example.com,03139345092,digital marketing,UET Lahore,2026-04-09,Under Review
2,Fatima Noor,NaN,03866306997,data science,Virtual University,2026-09-14,rejected
3,Hassan Ahmed,hassan.ahmed4@example.com,03655667651,data sci,Government College University,02/04/2026,Selected
4,Zainab Ali,zainab.ali5@example.com,031-489-2584,Data Analytics,Virtual University,2026-06-26,Under Review

## Standardizing Application Domains

Different spellings and short forms of application domains were mapped to consistent category names.

In [10]:
# Convert domain values to lowercase and remove extra spaces
df["Domain Applied"] = (
    df["Domain Applied"].str.strip().str.lower()
)

# Create a mapping dictionary
domain_mapping = {
    "web dev": "Web Development",
    "webdev": "Web Development",
    "web development": "Web Development",

    "digital marketing": "Digital Marketing",
    "digital mktg": "Digital Marketing",

    "data sci": "Data Science",
    "data science": "Data Science",

    "data analytics": "Data Analytics",
    "data analysis": "Data Analytics",

    "graphic design": "Graphic Design",
    "graphics": "Graphic Design"
}

# Apply the mapping
df["Domain Applied"] = df["Domain Applied"].map(domain_mapping)

print("Domain standardization completed.")

Domain standardization completed.

In [11]:
print("Unique domain categories:")
print(sorted(df["Domain Applied"].dropna().unique()))

print("\nNumber of domain categories:")
print(df["Domain Applied"].nunique())

print("\nMissing domain values:")
print(df["Domain Applied"].isnull().sum())

Unique domain categories:
['Data Analytics', 'Data Science', 'Digital Marketing', 'Graphic Design', 'Web Development']

Number of domain categories:
5

Missing domain values:
0

## Standardizing Status Values

Status values were cleaned by removing extra spaces and applying consistent capitalization.

## Dates and Phone Numbers

Application dates were converted to datetime format. Phone numbers were treated as text, and spaces and hyphens were removed.

In [12]:
# Convert application dates into datetime format
df["Application Date"] = pd.to_datetime(
    df["Application Date"],
    errors="coerce",
    format="mixed"
)

# Remove dashes and spaces from phone numbers
df["Phone"] = (
    df["Phone"]
    .astype("string")
    .str.replace("-", "", regex=False)
    .str.replace(" ", "", regex=False)
)

print("Updated data types:")
df.info()

Updated data types:
<class 'pandas.DataFrame'>
RangeIndex: 83 entries, 0 to 82
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Applicant Name    81 non-null     str
 1   Email             81 non-null     str
 2   Phone             82 non-null     string
 3   Domain Applied    83 non-null     str
 4   University        81 non-null     str
 5   Application Date  82 non-null     datetime64[us]
 6   Status            81 non-null     str
dtypes: datetime64[us](1), str(5), string(1)
memory usage: 4.7 KB

In [13]:
print("Missing or unreadable dates:")
print(df["Application Date"].isnull().sum())

print("\nPhone number examples:")
print(df["Phone"].head())

print("\nDate examples:")
print(df["Application Date"].head())

Missing or unreadable dates:
1

Phone number examples:
0     0328542679
1    03139345092
2    03866306997
3    03655667651
4     0314892584
Name: Phone, dtype: string

Date examples:
0   2026-02-06
1   2026-04-09
2   2026-09-14
3   2026-02-04
4   2026-06-26
Name: Application Date, dtype: datetime64[us]

## Final Data Check

The cleaned dataset was checked again for missing values, duplicate records, domain categories, and data types.

In [14]:
print("Final dataset shape:", df.shape)

print("\nMissing values:")
print(df.isnull().sum())

print("\nExact duplicate rows:", df.duplicated().sum())

print("\nDuplicate emails:", df.duplicated(subset=["Email"]).sum())

print("\nDomain categories:")
print(sorted(df["Domain Applied"].dropna().unique()))

print("\nDate data type:")
print(df["Application Date"].dtype)

display(df.head())

Final dataset shape: (83, 7)

Missing values:
Applicant Name      2
Email               2
Phone               1
Domain Applied      0
University          2
Application Date    1
Status              2
dtype: int64

Exact duplicate rows: 3

Duplicate emails: 5

Domain categories:
['Data Analytics', 'Data Science', 'Digital Marketing', 'Graphic Design', 'Web Development']

Date data type:
datetime64[us]

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
0,Ayesha Khan,ayesha.khan1@example.com,0328542679,Web Development,Government College University,2026-02-06,Selected
1,Ali Raza,ali.raza2@example.com,03139345092,Digital Marketing,UET Lahore,2026-04-09,Under Review
2,Fatima Noor,NaN,03866306997,Data Science,Virtual University,2026-09-14,rejected
3,Hassan Ahmed,hassan.ahmed4@example.com,03655667651,Data Science,Government College University,2026-02-04,Selected
4,Zainab Ali,zainab.ali5@example.com,0314892584,Data Analytics,Virtual University,2026-06-26,Under Review

## Exporting the Cleaned Dataset

The cleaned dataset was exported as a CSV file for future use.

In [15]:
df.to_csv("applicants_cleaned.csv", index=False)

print("Cleaned dataset exported successfully!")

Cleaned dataset exported successfully!

## Data Quality Summary

The dataset was cleaned by handling missing values, removing duplicates, standardizing text, and correcting date and phone formats. These steps helped make the data more consistent and suitable for further analysis.